#!/usr/bin/env bash
# Full local setup: deploy contracts to anvil, fund wallets, configure .env
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"

RPC_URL="${RPC_URL:-http://localhost:8545}"
# Anvil default accounts
DEPLOYER_KEY="0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
DEPLOYER_ADDR="0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
GAME_SERVER_KEY="0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d"
GAME_SERVER_ADDR="0x70997970C51812dc3A010C7d01b50e0d17dc79C8"

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🎰 Clawsino Local Setup"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

# --- 1. Wait for anvil ---
echo ""
echo "⏳ Waiting for anvil at $RPC_URL..."
for i in $(seq 1 30); do
    if cast chain-id --rpc-url "$RPC_URL" &>/dev/null; then
        echo "✅ Anvil is up (attempt $i)"
        break
    fi
    if [ "$i" = "30" ]; then
        echo "❌ Anvil not ready after 30s. Is it running?"
        echo "   Start it with: anvil --chain-id 8453 --block-time 1"
        exit 1
    fi
    sleep 1
done

# --- 2. Deploy contracts ---
echo ""
echo "🚀 Deploying contracts..."
cd "$ROOT_DIR/contracts"

OUTPUT=$(DEPLOYER_PRIVATE_KEY="$DEPLOYER_KEY" GAME_SERVER_ADDRESS="$GAME_SERVER_ADDR" \
    forge script script/Deploy.s.sol:Deploy \
    --rpc-url "$RPC_URL" \
    --broadcast \
    --private-key "$DEPLOYER_KEY" \
    -vvv 2>&1)

# Extract addresses
USDC_ADDR=$(echo "$OUTPUT" | grep "MockUSDC deployed:" | awk '{print $NF}')
PAYOUT_ADDR=$(echo "$OUTPUT" | grep "ClawsinoPayout deployed:" | awk '{print $NF}')
VERIFIER_ADDR=$(echo "$OUTPUT" | grep "FairnessVerifier deployed:" | awk '{print $NF}')

if [ -z "$USDC_ADDR" ] || [ -z "$PAYOUT_ADDR" ]; then
    echo "❌ Failed to extract contract addresses from deployment output"
    echo "$OUTPUT"
    exit 1
fi

echo "📋 Contract Addresses:"
echo "  USDC:      $USDC_ADDR"
echo "  Payout:    $PAYOUT_ADDR"
echo "  Verifier:  $VERIFIER_ADDR"

# --- 3. Fund bankroll ---
echo ""
echo "💰 Funding bankroll (100,000 USDC)..."
cast send "$USDC_ADDR" "approve(address,uint256)" "$PAYOUT_ADDR" 100000000000 \
    --rpc-url "$RPC_URL" --private-key "$DEPLOYER_KEY" > /dev/null
cast send "$PAYOUT_ADDR" "deposit(uint256)" 100000000000 \
    --rpc-url "$RPC_URL" --private-key "$DEPLOYER_KEY" > /dev/null
echo "✅ Bankroll funded"

# --- 4. Fund test wallets ---
TEST_WALLETS=(
    "0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC"
    "0x90F79bf6EB2c4f870365E785982E1f101E93b906"
    "0x15d34AAf54267DB7D7c367839AAf71A00a2C6A65"
    "0x9965507D1a55bcC2695C58ba16FB37d819B0A4dc"
)

echo ""
echo "🪙 Minting test USDC to wallets..."
for wallet in "${TEST_WALLETS[@]}"; do
    cast send "$USDC_ADDR" "mint(address,uint256)" "$wallet" 10000000000 \
        --rpc-url "$RPC_URL" --private-key "$DEPLOYER_KEY" > /dev/null
    BAL=$(cast call "$USDC_ADDR" "balanceOf(address)(uint256)" "$wallet" --rpc-url "$RPC_URL" 2>/dev/null || echo "?")
    echo "  ✅ $wallet — 10,000 USDC"
done

# --- 5. Write .env ---
echo ""
echo "📝 Updating .env..."
ENV_FILE="$ROOT_DIR/.env"

# Backup existing .env if present
[ -f "$ENV_FILE" ] && cp "$ENV_FILE" "$ENV_FILE.bak"

cat > "$ENV_FILE" <<EOF
# Clawsino Local Dev Environment
# Auto-generated by scripts/setup.sh on $(date -Iseconds)

# RPC
RPC_URL=$RPC_URL

# Deployer (Anvil account #0)
DEPLOYER_PRIVATE_KEY=$DEPLOYER_KEY
HOUSE_ADDRESS=$DEPLOYER_ADDR

# Game Server (Anvil account #1)
GAME_SERVER_PRIVATE_KEY=$GAME_SERVER_KEY
GAME_SERVER_ADDRESS=$GAME_SERVER_ADDR

# Contract Addresses
USDC_ADDRESS=$USDC_ADDR
PAYOUT_ADDRESS=$PAYOUT_ADDR
VERIFIER_ADDRESS=$VERIFIER_ADDR

# Server
PORT=3000

# x402 Mode: "demo" | "onchain" | unset (devMode)
X402_MODE=onchain

# CORS (comma-separated origins, or * for all)
CORS_ORIGINS=*
EOF

echo "✅ .env written"

# --- Summary ---
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✅ Setup complete!"
echo ""
echo "   Start the server:"
echo "     cd server && npm run dev"
echo ""
echo "   Or use Docker:"
echo "     docker compose up -d"
echo ""
echo "   Test wallets (10,000 USDC each):"
for wallet in "${TEST_WALLETS[@]}"; do
    echo "     $wallet"
done
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
